### ISSUE TITLE
Automatically create a task to watch for version updates of different charts

### ISSUE THREAD

**Issue by abhiyerra** [opszero/terraform-aws-kubespot#210]
Create a monthly task that updates the versions of:

 - https://github.com/opszero/terraform-aws-kubespot/blob/main/variables.tf#L426
 - https://github.com/opszero/terraform-aws-kubespot/blob/main/variables.tf#L384

Create a monthly cron job that creates an issue to update versions:
 - https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation

**Comment by abhiyerra** [comment]
Setup this to run once a month:

title: Update Helm Versions
body:

 - List all the helm charts in the repo that need to have their version updated


```
name: Weekly Team Sync
on:
  schedule:
    - cron: 20 07 * * 1

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "monalisa, doctocat, hubot"
          labels: "weekly sync, docs-team"
          title: "Team sync"
          body: |
            ### Version

            - [ ] Karpenter (https://github.com/opszero/terraform-aws-kubespot/blob/main/variables.tf#L426)

            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
