### ISSUE TITLE
Add Default Karpenter Config

### ISSUE THREAD

**Issue by abhiyerra** [opszero/terraform-aws-kubespot#250]
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium", "t3a.medium"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  provider:
    securityGroupSelector:
      'kubernetes.io/cluster/opszero': 'owned'
    subnetSelector:
      Name: opszero-public
  ttlSecondsUntilExpired: 6400
```
