### ISSUE TITLE
Setup to use gp3

### ISSUE THREAD

**Issue by abhiyerra** [opszero/terraform-aws-kubespot#270]
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
spec:
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
```
